### ISSUE TITLE
Naming Consistency in the AddOn List

### ISSUE THREAD

**Issue by Frurox** [N6REJ/AdiBags_Shadowlands_Inscription#10]
This is not an issue, but more something that has to do with Naming Consistency and hope is a simple and fast fix.
These look good
<img width="317" alt="image" src="https://user-images.githubusercontent.com/47403751/202544307-b198883c-9b8e-4ae0-a464-b89c6ca7740b.png">
And this one is missing the "AdiBags - "
<img width="186" alt="image" src="https://user-images.githubusercontent.com/47403751/202544612-15be601a-20ef-425d-a17a-d24c1a00c51f.png">

**Comment by N6REJ** [comment]
Thanks for the report.  Should be resolved with 2022.11.18

**Comment by Frurox** [comment]
Thanks! Keep up the great work in taking these up, if you can do more that are out of date and make them your own would be great!

**Comment by N6REJ** [comment]
Released hearthstones last night.
https://www.curseforge.com/wow/addons/adibags_bears_hearthstones
https://addons.wago.io/addons/adibags-bears-hearthstones
